RD-15380: Strip HTTP headers from errors (#25)
The JIRA API throws `ApiException`, which contains both a useful message
and HTTP headers in a side field. Its implementation of `.getMessage`
concatenates the message _and headers_. That's why the error message is
so large.
```
ERROR:  Invalid argument
DETAIL:  {"code": "INVALID_ARGUMENT", "das_name": "localhost:50051",
"das_type": "jira", "das_url": "localhost:50051", "table_name": "jira_user",
"cause": "<_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus =
StatusCode.INVALID_ARGUMENT\n\tdetails =
\"com.rawlabs.das.jira.rest.platform.ApiException: Message: \nHTTP response
code: 403\nHTTP response body:
{\"errorMessages\":[\"error.no-permission\"],\"errors\":{}}\nHTTP response
headers: {atl-request-id=[23638b90-e70d-4304-bc92-06c1be1fb35e],
atl-traceid=[23638b90e70d4304bc9206c1be1fb35e], cache-control=[no-store,
no-cache], content-type=[application/json;charset=UTF-8], date=[Wed, 26 Feb
2025 10:06:28 GMT], nel=[{\"failure_fraction\": 0.001, \"include_subdomains\":
true, \"max_age\": 600, \"report_to\": \"endpoint-1\"}],
report-to=[{\"endpoints\": [{\"url\":
\"https://dz8aopenkvv6s.cloudfront.net\"}], \"group\": \"endpoint-1\",
\"include_subdomains\": true, \"max_age\": 600}], server=[AtlassianEdge],
server-timing=[atl-edge;dur=105,atl-edge-internal;dur=19,atl-edge-upstream;dur=86,atl-edge-pop;desc=\"aws-us-west-2\"],
set-cookie=[atlassian.xsrf.token=f472ecf4334792d9776c8377a9c73315073a2da7_lout;
Path=/; SameSite=None; Secure], strict-transport-security=[max-age=63072000;
includeSubDomains; preload], timing-allow-origin=[*], via=[1.1
54ba4737103cb6263e414e602fbbe752.cloudfront.net (CloudFront)],
x-amz-cf-id=[x6ag0TnQ5mjeB1O-hfdLlT4_9vLVYHNvA5KLNlm19RNMG5S46bWuiQ==],
x-amz-cf-pop=[MRS52-P1], x-arequestid=[272d0ce7836dba60c20806bdcf3c585b],
x-cache=[Error from cloudfront], x-content-type-options=[nosniff],
x-seraph-loginreason=[AUTHENTICATED_FAILED], x-xss-protection=[1;
mode=block]}\"\n\tdebug_error_string = \"UNKNOWN:Error received from peer
{created_time:\"2025-02-26T11:06:28.188827+01:00\", grpc_status:3,
grpc_message:\"com.rawlabs.das.jira.rest.platform.ApiException: Message:
\\nHTTP response code: 403\\nHTTP response body:
{\\\"errorMessages\\\":[\\\"error.no-permission\\\"],\\\"errors\\\":{}}\\nHTTP
response headers: {atl-request-id=[23638b90-e70d-4304-bc92-06c1be1fb35e],
atl-traceid=[23638b90e70d4304bc9206c1be1fb35e], cache-control=[no-store,
no-cache], content-type=[application/json;charset=UTF-8], date=[Wed, 26 Feb
2025 10:06:28 GMT], nel=[{\\\"failure_fraction\\\": 0.001,
\\\"include_subdomains\\\": true, \\\"max_age\\\": 600, \\\"report_to\\\":
\\\"endpoint-1\\\"}], report-to=[{\\\"endpoints\\\": [{\\\"url\\\":
\\\"https://dz8aopenkvv6s.cloudfront.net\\\"}], \\\"group\\\":
\\\"endpoint-1\\\", \\\"include_subdomains\\\": true, \\\"max_age\\\": 600}],
server=[AtlassianEdge],
server-timing=[atl-edge;dur=105,atl-edge-internal;dur=19,atl-edge-upstream;dur=86,atl-edge-pop;desc=\\\"aws-us-west-2\\\"],
set-cookie=[atlassian.xsrf.token=f472ecf4334792d9776c8377a9c73315073a2da7_lout;
Path=/; SameSite=None; Secure], strict-transport-security=[max-age=63072000;
includeSubDomains; preload], timing-allow-origin=[*], via=[1.1
54ba4737103cb6263e414e602fbbe752.cloudfront.net (CloudFront)],
x-amz-cf-id=[x6ag0TnQ5mjeB1O-hfdLlT4_9vLVYHNvA5KLNlm19RNMG5S46bWuiQ==],
x-amz-cf-pop=[MRS52-P1], x-arequestid=[272d0ce7836dba60c20806bdcf3c585b],
x-cache=[Error from cloudfront], x-content-type-options=[nosniff],
x-seraph-loginreason=[AUTHENTICATED_FAILED], x-xss-protection=[1;
mode=block]}\"}\"\n>"}
```
With the patch, it's shorter since we only either propagate the response
body only, or a generic message. This is fixed when catching
`ApiException`, we throw an SDK one.

If triggering authentication errors by registering a DAS with wrong
credentials, some endpoint succeed (those which don't require
authentication), possibly returning fewer rows (e.g. only public items).
But some fail. For example with 400, 401 or 403.

What the patch implements:

We never propagate HTTP headers and that kind of metadata. That shortens
the message string. We only consider the message body, which I believe
is the useful part of the error.

There's some handling of the HTTP code:
* 400: we propagate the error's body in a
`DASSdkInvalidArgumentException`, because it should have useful detail.
In the examples I triggered, the message is a json data structure. The
API doesn't document the format of that JSON. I see it sometimes shown
as an example but it's not specified.
* 401: I see it coming systematically with "Client must be authenticated
to access this resource". The message is clean, but since the API
doesn't document it, it's rewritten and wrapped in
`DASSdkUnauthenticatedException`.
* 403: I saw it coming with a JSON body which structure isn't
documented. Since we know the HTTP 403 code, the message is rewritten in
our code and propagated with `DASSdkPermissionDeniedException`.
* others: we propagate the error's body.

JQL syntax/semantic errors are leading to 400, which is propagated as
"invalid argument". In https://github.com/raw-labs/das-jira/pull/17 we
fix JQL generation, but there are some errors we can hardly avoid, that
lead to 400. For example this query filters on a invalid
`status_category`, which means it doesn't match any row.
```sql
SELECT *
FROM jira.jira_issue
WHERE status_category = 'tralala' -- this is a silly category
```
This leads to JQL: `statusCategory = "tralala"` which fails with 400.
```
ERROR:  {"errorMessages":["The value 'tralala' does not exist for the field 
'statusCategory'."],"warningMessages":[]}                                                                          
DETAIL:  {"code": "INVALID_ARGUMENT", "message": "{\"errorMessages\":[\"The
value 'tralala' does not exist for the field
'statusCategory'.\"],\"warningMessages\":[]}", "das_name": "localhost:50051",
"das_type": "jira", "das_url": "localhost:50051", "table_name": "jira_issue",
"cause": "<_MultiThreadedRendezvous of RPC that terminated with:\n\tstatus =
StatusCode.INVALID_ARGUMENT\n\tdetails = \"{\"errorMessages\":[\"The value
'tralala' does not exist for the field
'statusCategory'.\"],\"warningMessages\":[]}\"\n\tdebug_error_string =
\"UNKNOWN:Error received from peer
{grpc_message:\"{\\\"errorMessages\\\":[\\\"The value \\'tralala\\' does not
exist for the field \\'statusCategory\\'.\\\"],\\\"warningMessages\\\":[]}\",
grpc_status:3, created_time:\"2025-02-28T15:18:26.003452+01:00\"}\"\n>"}
```
> [!NOTE]
> The JSON structure I see is systematically an object with an
`errorMessages` key that is a list of error strings.
> I haven't implemented an attempt to extract and concatenate those.
Maybe we could do that?
Legitimate queries leading to bad JQL because of a bug also hit 400 and
are also propagated to users (while it's technically a bug in the DAS).